const APP_ID='preset-visual-editor';
const state={old:null,new:null,oldName:'',newName:'',tab:'old',active:{old:null,new:null},query:'',enabled:'all',dirty:{old:false,new:false}};
const clone=value=>structuredClone(value);
const byId=preset=>new Map((preset?.prompts||[]).map(prompt=>[prompt.identifier,prompt]));
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node;}
function button(text,action,className){const node=el('button','menu_button '+(className||''),text);node.type='button';node.dataset.action=action;return node;}
function validate(data){if(!data||!Array.isArray(data.prompts))throw new Error('不是有效的 SillyTavern OpenAI 预设：缺少 prompts 数组。');const ids=new Set();for(const p of data.prompts){if(!p||typeof p.identifier!=='string'||!p.identifier)throw new Error('存在没有 identifier 的条目。');if(ids.has(p.identifier))throw new Error('条目 ID 重复：'+p.identifier);ids.add(p.identifier);}return data;}
function currentPreset(){return state[state.tab];}
function currentName(){return state[state.tab+'Name'];}
function orderedPrompts(preset){if(!preset)return[];const prompts=byId(preset),seen=new Set(),result=[];for(const group of preset.prompt_order||[]){for(const item of group.order||[]){const prompt=prompts.get(item.identifier);if(prompt&&!seen.has(item.identifier)){result.push(prompt);seen.add(item.identifier);}}}for(const prompt of preset.prompts){if(!seen.has(prompt.identifier))result.push(prompt);}return result;}
function filteredPrompts(){const query=state.query.trim().toLocaleLowerCase();return orderedPrompts(currentPreset()).filter(prompt=>{if(state.enabled==='enabled'&&prompt.enabled===false)return false;if(state.enabled==='disabled'&&prompt.enabled!==false)return false;if(!query)return true;return [prompt.name,prompt.identifier,prompt.role,prompt.content].join('\n').toLocaleLowerCase().includes(query);});}
function createShell(){let dialog=document.getElementById(APP_ID+'-dialog');if(dialog)return dialog;dialog=el('dialog','pve-dialog');dialog.id=APP_ID+'-dialog';const app=el('div','pve-app');dialog.append(app);
const header=el('header','pve-header');const title=el('div');title.append(el('h2','', '预设条目编辑器'),el('p','', '旧版与新版分别浏览、编辑和导出'));header.append(title,button('导出当前预设','export','pve-primary'),button('×','close','pve-close'));app.append(header);
const imports=el('section','pve-imports');imports.append(fileBox('old','旧版预设'),fileBox('new','新版预设'));app.append(imports);
const tabs=el('nav','pve-tabs');tabs.append(tabButton('old','旧版条目'),tabButton('new','新版条目'));app.append(tabs);
const toolbar=el('section','pve-toolbar');const search=el('input');search.type='search';search.placeholder='搜索名称、ID、角色或正文';search.dataset.action='search';const enabled=el('select');enabled.dataset.action='enabled';[['all','全部状态'],['enabled','仅启用'],['disabled','仅禁用']].forEach(pair=>{const option=el('option','',pair[1]);option.value=pair[0];enabled.append(option);});toolbar.append(search,enabled,button('新建条目','new-entry'));app.append(toolbar);
app.append(el('section','pve-summary','请分别导入需要查看的预设。'));const main=el('main','pve-main');main.append(el('section','pve-list'),el('section','pve-detail'));app.append(main);dialog.addEventListener('click',onClick);dialog.addEventListener('change',onChange);dialog.addEventListener('input',onInput);document.body.append(dialog);return dialog;}
function fileBox(key,title){const label=el('label','pve-file');label.append(el('span','',title));const name=el('strong','', '选择 JSON');name.dataset.fileName=key;label.append(name);const input=el('input');input.type='file';input.accept='.json,application/json';input.dataset.file=key;label.append(input);return label;}
function tabButton(key,title){const node=button(title,'tab','pve-tab');node.dataset.tab=key;return node;}
async function loadFile(key,file){try{state[key]=validate(JSON.parse(await file.text()));state[key+'Name']=file.name;state.dirty[key]=false;state.active[key]=state[key].prompts[0]?.identifier||null;document.querySelector('[data-file-name="'+key+'"]').textContent=file.name+' · '+state[key].prompts.length+' 条';state.tab=key;render();}catch(error){window.toastr?toastr.error(error.message,'导入失败'):alert(error.message);}}
function render(){document.querySelectorAll('.pve-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.tab===state.tab));const preset=currentPreset(),list=document.querySelector('.pve-list'),detail=document.querySelector('.pve-detail');list.replaceChildren();detail.replaceChildren();if(!preset){document.querySelector('.pve-summary').textContent=(state.tab==='old'?'旧版':'新版')+'预设尚未导入。';detail.append(el('div','pve-empty','导入当前标签对应的预设后即可查看和编辑条目。'));return;}const prompts=filteredPrompts();document.querySelector('.pve-summary').textContent=(state.tab==='old'?'旧版':'新版')+' · '+preset.prompts.length+' 条 · 当前显示 '+prompts.length+' 条'+(state.dirty[state.tab]?' · 有未导出的修改':'');for(const prompt of prompts)list.append(promptRow(prompt));const id=state.active[state.tab];if(id&&byId(preset).has(id))renderEditor(id);else detail.append(el('div','pve-empty','从左侧选择一个条目查看和编辑。'));}
function promptRow(prompt){const row=el('article','pve-row'+(state.active[state.tab]===prompt.identifier?' active':''));const open=el('button','pve-open');open.type='button';open.dataset.open=prompt.identifier;open.append(el('span','pve-name',prompt.name||'(未命名)'),el('code','',prompt.identifier));row.append(open,el('span','pve-role',prompt.role||'system'),el('span','pve-status '+(prompt.enabled===false?'off':'on'),prompt.enabled===false?'禁用':'启用'));return row;}
function makeInput(labelText,name,value,type='text'){const label=el('label','pve-control');label.append(el('span','',labelText));const input=el('input');input.name=name;input.type=type;if(type==='checkbox')input.checked=value!==false;else input.value=value??'';label.append(input);return label;}
function makeJsonField(labelText,name,value){const label=el('label','pve-control pve-wide');label.append(el('span','',labelText));const area=el('textarea','pve-json');area.name=name;area.value=value===undefined?'':JSON.stringify(value,null,2);label.append(area);return label;}
function renderEditor(id){const prompt=byId(currentPreset()).get(id),detail=document.querySelector('.pve-detail'),form=el('form','pve-editor');form.dataset.id=id;const head=el('div','pve-editor-head');const info=el('div');info.append(el('h3','',prompt.name||'(未命名)'),el('code','',prompt.identifier));head.append(info,button('删除条目','delete','pve-danger'));form.append(head);
const grid=el('div','pve-grid');grid.append(makeInput('名称','name',prompt.name),makeInput('角色','role',prompt.role),makeInput('启用','enabled',prompt.enabled,'checkbox'),makeInput('注入位置','injection_position',prompt.injection_position,'number'),makeInput('注入深度','injection_depth',prompt.injection_depth,'number'),makeInput('注入顺序','injection_order',prompt.injection_order,'number'),makeInput('系统提示','system_prompt',prompt.system_prompt,'checkbox'),makeInput('标记条目','marker',prompt.marker,'checkbox'),makeInput('禁止覆盖','forbid_overrides',prompt.forbid_overrides,'checkbox'));
const trigger=prompt.injection_trigger;grid.append(makeJsonField('注入触发条件（JSON）','injection_trigger',trigger));form.append(grid);const contentLabel=el('label','pve-control pve-content');contentLabel.append(el('span','', '条目正文'));const content=el('textarea','pve-content-area');content.name='content';content.value=prompt.content||'';contentLabel.append(content);form.append(contentLabel);
const extra=el('details','pve-extra');extra.append(el('summary','', '查看完整条目 JSON'));const json=el('textarea','pve-full-json');json.name='full_json';json.value=JSON.stringify(prompt,null,2);extra.append(json);form.append(extra);const actions=el('div','pve-editor-actions');const save=button('保存条目','save','pve-primary');save.type='submit';actions.append(save);form.append(actions);form.addEventListener('submit',savePrompt);detail.append(form);}
function parseOptionalJson(text,field){if(!text.trim())return undefined;try{return JSON.parse(text);}catch{throw new Error(field+' 不是有效 JSON。');}}
function savePrompt(event){event.preventDefault();const form=event.currentTarget,data=new FormData(form),preset=currentPreset(),index=preset.prompts.findIndex(item=>item.identifier===form.dataset.id);try{let prompt=parseOptionalJson(String(data.get('full_json')),'完整条目 JSON');if(!prompt||typeof prompt!=='object')throw new Error('完整条目 JSON 必须是对象。');prompt.identifier=form.dataset.id;prompt.name=String(data.get('name')||'');prompt.role=String(data.get('role')||'system');prompt.enabled=data.get('enabled')==='on';prompt.system_prompt=data.get('system_prompt')==='on';prompt.marker=data.get('marker')==='on';prompt.forbid_overrides=data.get('forbid_overrides')==='on';prompt.content=String(data.get('content')||'');['injection_position','injection_depth','injection_order'].forEach(field=>{const value=String(data.get(field)||'');if(value==='')delete prompt[field];else prompt[field]=Number(value);});const trigger=parseOptionalJson(String(data.get('injection_trigger')||''),'注入触发条件');if(trigger===undefined)delete prompt.injection_trigger;else prompt.injection_trigger=trigger;preset.prompts[index]=prompt;syncOrder(prompt.identifier,prompt.enabled);state.dirty[state.tab]=true;render();window.toastr&&toastr.success('条目已保存');}catch(error){window.toastr?toastr.error(error.message,'保存失败'):alert(error.message);}}
function syncOrder(id,enabled){const preset=currentPreset();if(!Array.isArray(preset.prompt_order))preset.prompt_order=[{character_id:100001,order:[]}];if(!preset.prompt_order[0])preset.prompt_order[0]={character_id:100001,order:[]};const order=preset.prompt_order[0].order||(preset.prompt_order[0].order=[]),item=order.find(entry=>entry.identifier===id);if(item)item.enabled=enabled;else order.push({identifier:id,enabled});}
function newEntry(){const preset=currentPreset();if(!preset)return;let id='custom-'+Date.now();while(byId(preset).has(id))id+='-1';const prompt={identifier:id,name:'新条目',enabled:true,injection_position:0,injection_depth:4,injection_order:100,role:'system',content:'',system_prompt:false,marker:false,forbid_overrides:false,injection_trigger:[]};preset.prompts.push(prompt);syncOrder(id,true);state.active[state.tab]=id;state.dirty[state.tab]=true;render();}
function deleteEntry(){const preset=currentPreset(),id=state.active[state.tab];if(!preset||!id||!confirm('确定删除当前条目吗？'))return;preset.prompts=preset.prompts.filter(prompt=>prompt.identifier!==id);for(const group of preset.prompt_order||[])group.order=(group.order||[]).filter(item=>item.identifier!==id);state.active[state.tab]=preset.prompts[0]?.identifier||null;state.dirty[state.tab]=true;render();}
function exportPreset(){const preset=currentPreset();if(!preset)return;const blob=new Blob([JSON.stringify(preset,null,2)],{type:'application/json;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=(currentName()||state.tab+'-preset').replace(/\.json$/i,'')+'-已编辑.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);state.dirty[state.tab]=false;render();}
function onClick(event){const target=event.target.closest('button');if(!target)return;const action=target.dataset.action;if(action==='close')event.currentTarget.close();if(action==='export')exportPreset();if(action==='new-entry')newEntry();if(action==='delete')deleteEntry();if(action==='tab'){state.tab=target.dataset.tab;state.query='';const search=document.querySelector('[data-action=search]');if(search)search.value='';render();}if(target.dataset.open){state.active[state.tab]=target.dataset.open;render();}}
function onChange(event){if(event.target.dataset.file&&event.target.files[0])loadFile(event.target.dataset.file,event.target.files[0]);if(event.target.dataset.action==='enabled'){state.enabled=event.target.value;render();}}
function onInput(event){if(event.target.dataset.action==='search'){state.query=event.target.value;render();}}
function addMenu(){const menu=document.getElementById('extensionsMenu');if(!menu||document.getElementById(APP_ID+'-button'))return false;const entry=el('div','list-group-item flex-container flexGap5 interactable');entry.id=APP_ID+'-button';entry.tabIndex=0;entry.append(el('span','fa-solid fa-pen-to-square'),el('span','', '预设条目编辑器'));entry.addEventListener('click',()=>createShell().showModal());menu.append(entry);return true;}
jQuery(()=>{if(!addMenu()){const observer=new MutationObserver(()=>{if(addMenu())observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});}});
